# Generated by Django 3.1.7 on 2021-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_settings', '0002_auto_20200826_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_type',
            field=models.CharField(choices=[('bool', 'bool'), ('date', 'date'), ('datetime', 'datetime'), ('decimal', 'decimal'), ('duration', 'duration'), ('email', 'email'), ('file', 'file'), ('float', 'float'), ('image', 'image'), ('int', 'int'), ('string', 'string'), ('text', 'text'), ('time', 'time'), ('uuid', 'uuid'), ('url', 'url')], max_length=20, verbose_name='Type'),
        ),
    ]
